<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>9db3ed31-1620-43bc-bb31-aa82d1320c14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='page-topbar']/div/div/div[2]/div/a[2]/span[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.logo.logo-light > span.logo-lg > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4574db67-c25e-4bed-abd8-ad79c42418a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://caraorbis.s3.ap-south-1.amazonaws.com/820c52bd-a546-4bd6-9227-c4b783153adf_logo.png</value>
      <webElementGuid>7116711b-af30-437e-a63d-95a8204a84c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>70</value>
      <webElementGuid>f9c3a01d-afba-45b8-8841-98e664f4616d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-topbar&quot;)/div[@class=&quot;navbar-header&quot;]/div[@class=&quot;container-fluid&quot;]/div[2]/div[@class=&quot;navbar-brand-box&quot;]/a[@class=&quot;logo logo-light&quot;]/span[@class=&quot;logo-lg&quot;]/img[1]</value>
      <webElementGuid>278ad877-ea0e-4a25-aec3-56c4a1c8b415</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='page-topbar']/div/div/div[2]/div/a[2]/span[2]/img</value>
      <webElementGuid>fac4e8b8-f6d6-4e9b-acd6-b1a08329644b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://caraorbis.s3.ap-south-1.amazonaws.com/820c52bd-a546-4bd6-9227-c4b783153adf_logo.png')])[4]</value>
      <webElementGuid>7c7db22a-329b-481b-a0cb-297e2adba2b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span[2]/img</value>
      <webElementGuid>2e267b5b-4c8e-4345-ae10-a088e872f58b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://caraorbis.s3.ap-south-1.amazonaws.com/820c52bd-a546-4bd6-9227-c4b783153adf_logo.png']</value>
      <webElementGuid>2ecb2ef5-7d50-42f5-8804-26fef88e449a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
